# Harmony Jekyll theme general configurations 

# Base URL
# baseurl: /harmony

# Site live URL
# url: http://gayan.me

# Localhost 
url: https://andreipall.github.io  

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Andrei Pall
  # Little description about your site
  description: Linux Software Development
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and 
  # in your feed.xml site description.
  meta_description: > # 
   Web Development Blog
  meta_keywords: > # 
   java, php, spring, ruby, rails, web, development, blog, programming
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Andrei Pall
    email: andreipall@yahoo.com
    url: http://andreipall.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-48549180-1

  # Profile links, leave blank to ignore
  social: 
    github: andreipall
    #twitter: integersoft
    facebook: andreipall
    #gplus: /u/0/102531918494446984072
    #dribble: andreipall
    #pinterest: pallandrei1
  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings 
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge 

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
